version: '3'

services:

  postgresql:
    image: postgres
    container_name: postgresdb
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb1
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - 8000:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: your email address
      PGADMIN_DEFAULT_PASSWORD: something password
    hostname: pgadmin4
    depends_on:
      - postgres
    restart: always